name = "perry-api"
main = "src/worker.js"
compatibility_date = "2024-02-14"

[[d1_databases]]
binding = "DB"
database_name = "perry-auth"
database_id = "8f0fbe1b-27e4-4bdf-ae42-4068af6c8c73"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "perry-photos"

[env.development]
name = "perry-api-dev"
workers_dev = true

[env.production]
name = "perry-api"
route = "api.perry.click/*"
