name = "perry-api"
main = "src/worker.js"
compatibility_date = "2024-02-14"

# Bunny.net Storage API credentials
[vars]
BUNNY_STORAGE_ZONE = "perryclick"
BUNNY_STORAGE_API_KEY = "07db7c56-22d3-4767-acf11d558392-ddb4-435f"
BUNNY_STORAGE_ENDPOINT = "ny.storage.bunnycdn.com"

[[d1_databases]]
binding = "DB"
database_name = "perry-auth"
database_id = "8f0fbe1b-27e4-4bdf-ae42-4068af6c8c73"

[env.development]
name = "perry-api-dev"
workers_dev = true

[env.production]
name = "perry-api"
route = "api.perry.click/*"
