name: Deploy All

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'cloudflare-worker/') || contains(github.event.head_commit.added, 'cloudflare-worker/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: cloudflare-worker/package-lock.json
          
      - name: Install Worker dependencies
        run: |
          cd cloudflare-worker
          npm ci
          
      - name: Deploy Cloudflare Worker
        run: |
          cd cloudflare-worker
          npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
  build-frontend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'src/') || contains(github.event.head_commit.added, 'src/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json
          
      - name: Install Frontend dependencies
        run: npm ci
        
      - name: Build Angular app
        run: npm run build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: dist/ 