name: Deploy Cloudflare Worker

on:
  push:
    branches: [main]
    paths: ['cloudflare-worker/**']
  pull_request:
    branches: [main]
    paths: ['cloudflare-worker/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: cloudflare-worker/package-lock.json
          
      - name: Install dependencies
        run: |
          cd cloudflare-worker
          npm ci
          
      - name: Deploy to Cloudflare Workers
        run: |
          cd cloudflare-worker
          npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} 